<?php


namespace agent_models\traits;


use agent_models\Employee;
use agent_models\User;

/**
 * Trait YiiModelValidatePassWordTrait
 * @package agent_models\traits
 */
trait YiiModelValidateAdminsPassWordTrait
{

    public $admins;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $attribute
     * @param $params
     */
    public function validateLoginUserPassword($attribute , $params)
    {
        if (empty($this->$attribute)) {
            $this->addError($attribute , '密码不能为空');
            return;
        }
        if (!$this->hasErrors()) {
            $user = $this->getUser();
            if (!$user) {
                $this->addError($attribute , '用户不存在');
                return;
            }
            if (!$user->validatePassword($this->$attribute)) {

                $this->addError($attribute , '密码错误');
            }
        }
    }

    /**
     * @param $attribute
     * @param $params
     */
    public function validateLoginUserPayPassword($attribute , $params)
    {
        if (empty($this->$attribute)) {
            $this->addError($attribute , '密码不能为空');
            return;
        }
        if (!$this->hasErrors()) {
            $user = $this->getUser();
            if (!$user) {
                $this->addError($attribute , '用户不存在');
                return;
            }
            if (!$user->validatePassword($this->$attribute)) {
                $this->addError($attribute , '密码错误');
                return;
            }
        }

    }


    /**
     * @return Employee|User|\yii\web\IdentityInterface|null
     */
    private function getUser()
    {
        return $this->admins ?: \Yii::$app->user->identity;
    }
}