<?php


namespace agent_models\traits;


trait YiiModelTrait
{
    public function getOneErrorMsg(){
        return current($this->getFirstErrors());
    }

    public function load($data , $formName = '')
    {
        $load=parent::load($data , $formName);
//        if(!$load){
//            $this->addError('load_data','请填写正确的信息');
//        }
        return $load;// TODO: Change the autogenerated stub
    }


    public function whenNotErrors($model, $attribute){
        return !$this->hasErrors();
    }

    public function loadAndValidate($data, $formName = '')
    {
        $this->load($data, $formName);
        return $this->validate();
    }


    public static function getLongIp($ip){
        return long2ip($ip);
    }

    public static function getUserIpAsInt(){
        return ip2long(\Yii::$app->request->userIP);
    }

    public static function getNowTime(){
        return date('Y-m-d H:i:s');
    }
}